title: "Ngulikin"
author:
  name: irfnrdh
  email: irfnrdh@gmail.com

description: >
  A learning log by Irfannur Diah (@irfnrdh)

remote_theme: "jekyll/minima@1e8a445"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark

  nav_pages:
    - about.md

  show_excerpts: true

  # Optional: Customize the date format if needed
  # date_format: "%b %d, %Y"

  social_links:
    - title: TIL
      icon: github
      url: "https://github.com/irfnrdh/til"
